# Generated by Django 3.2.9 on 2022-01-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211215_1239'),
        ('posts', '0003_category_slug'),
    ]

    operations = [
    ]
