# Generated by Django 3.2.9 on 2022-01-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220109_2115'),
        ('posts', '0004_merge_0003_auto_20211215_1239_0003_category_slug'),
    ]

    operations = [
    ]
