# Generated by Django 3.2.9 on 2022-01-12 13:11
from django.db import migrations


def run_query(apps, schema_editor):
    Category = apps.get_model("posts", "Category")
    SubCategory = apps.get_model("posts", "SubCategory")

    for category in Category.objects.all():
        category.save()

    for sub_category in SubCategory.objects.all():
        sub_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image'),
    ]

    operations = [
        migrations.RunPython(run_query)
    ]
