# Generated by Django 3.2.9 on 2022-01-12 13:26

from django.db import migrations, models
from django.utils.text import slugify


def run_query(apps, schema_editor):
    Category = apps.get_model("posts", "Category")
    SubCategory = apps.get_model("posts", "SubCategory")

    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()

    for sub_category in SubCategory.objects.all():
        sub_category.slug = slugify(sub_category.name)
        sub_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_update_categories_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.RunPython(run_query)
    ]
