# Generated by Django 3.2.9 on 2022-01-12 13:46

from django.db import migrations
from django.utils.text import slugify


def run_query(apps, schema_editor):
    Category = apps.get_model("posts", "Category")
    SubCategory = apps.get_model("posts", "SubCategory")

    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()

    for sub_category in SubCategory.objects.all():
        sub_category.slug = slugify(sub_category.name)
        sub_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_subcategory_slug'),
    ]

    operations = [
        migrations.RunPython(run_query)
    ]
