# Generated by Django 3.2.9 on 2022-02-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_exerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='exerpt',
            new_name='excerpt',
        ),
    ]
