# Generated by Django 3.2.9 on 2022-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220219_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbody',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
