# Generated by Django 3.2.9 on 2022-03-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postbody_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbody',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Section Title'),
        ),
    ]
