# Generated by Django 3.2.9 on 2022-03-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postbody_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(0, 'Themes'), (1, 'Sectors')], default=0, max_length=100),
        ),
    ]
