# Generated by Django 3.2.9 on 2022-03-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_postbody_title'),
        ('posts', '0015_auto_20220301_1747'),
    ]

    operations = [
    ]
