# Generated by Django 3.2.9 on 2022-03-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_merge_20220303_1429'),
        ('posts', '0016_merge_20220303_1550'),
    ]

    operations = [
    ]
