# Generated by Django 3.2.9 on 2022-03-11 11:43

from django.db import migrations
from django.utils.text import slugify


def slugify_all_post_bodies(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PostBody = apps.get_model('posts', 'PostBody')
    for post_body in PostBody.objects.all():
        post_body.slug = slugify(post_body.title)
        post_body.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_postbody_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_all_post_bodies),
    ]
