# Generated by Django 3.2.9 on 2022-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20220311_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
