# Generated by Django 3.2.9 on 2022-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_post_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
        migrations.AddField(
            model_name='post',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='posts.Sector'),
        ),
        migrations.AddField(
            model_name='post',
            name='themes',
            field=models.ManyToManyField(blank=True, to='posts.Theme'),
        ),
    ]
