# Generated by Django 3.2.9 on 2022-07-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20220324_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Sector'),
        ),
        migrations.AlterField(
            model_name='post',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Theme'),
        ),
        migrations.AlterField(
            model_name='postbody',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='posts.post'),
        ),
    ]
