# Generated by Django 3.2.9 on 2022-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_post_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Company'),
        ),
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Product'),
        ),
        migrations.AddField(
            model_name='post',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Region'),
        ),
    ]
