# Generated by Django 3.2.9 on 2022-06-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_premium'),
    ]

    operations = [
    ]
