# Generated by Django 3.2.9 on 2022-03-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='article',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='events'),
        ),
    ]
