# Generated by Django 3.2.9 on 2022-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220322_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('presentation', 'presentation')], max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
