# Generated by Django 3.2.9 on 2022-03-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databanks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databank',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databank',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
